import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:dartz/dartz.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:mezgebe_sibhat/features/songs/data/local/cached_song_data.dart';
import 'package:mezgebe_sibhat/features/songs/data/models/server_model.dart';
import 'package:path_provider/path_provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:mezgebe_sibhat/core/error/failure.dart';
import 'package:mezgebe_sibhat/core/network/network_info_impl.dart';
import 'package:mezgebe_sibhat/features/songs/data/local/song_model.dart';
import 'package:mezgebe_sibhat/features/songs/domain/entities/SongModel.dart';
import 'package:mezgebe_sibhat/features/songs/domain/repository/song_repo.dart';
import 'package:http/http.dart' as http;

// ---------------------------------------------------------------------------
// Top-level helpers (must be top-level/static, not instance methods, so they
// can be handed to `compute()` and run on a background isolate).
// ---------------------------------------------------------------------------

int _sortByName(SongModel a, SongModel b) {
  final regex = RegExp(r'^(\d+)-?');
  final aMatch = regex.firstMatch(a.name);
  final bMatch = regex.firstMatch(b.name);

  if (aMatch != null && bMatch != null) {
    final aNum = int.parse(aMatch.group(1)!);
    final bNum = int.parse(bMatch.group(1)!);
    if (aNum != bNum) return aNum.compareTo(bNum);
  } else if (aMatch != null) {
    return -1;
  } else if (bMatch != null) {
    return 1;
  }

  return a.name.compareTo(b.name);
}

List<SongModel> _sortRecursive(List<SongModel> list) {
  for (var song in list) {
    if (song.children.isNotEmpty) {
      song.children = _sortRecursive(song.children);
    }
  }
  list.sort(_sortByName);
  return list;
}

/// Everything the background isolate hands back: the sorted tree AND the
/// pre-built URL lookup, so the main isolate does zero tree-walking.
class _ParsedSongs {
  final List<SongModel> tree;
  final Map<String, Map<AudioServer, String>> lookup;
  _ParsedSongs(this.tree, this.lookup);
}

void _buildLookup(
  Map<String, Map<AudioServer, String>> lookup,
  List<SongModel> songs, [
  String? parentId,
]) {
  for (final song in songs) {
    if (song.isAudio && song.urls.isNotEmpty && parentId != null) {
      final key = '$parentId|${song.name}';
      lookup[key] = song.urls.map(
        (serverName, url) =>
            MapEntry(AudioServer.values.byName(serverName), url),
      );
    }
    if (song.children.isNotEmpty) {
      _buildLookup(lookup, song.children, song.id);
    }
  }
}

/// Runs entirely on a background isolate: UTF-8 decode + JSON decode + build
/// the SongModel tree + sort it + build the URL lookup, all in one shot.
/// Takes raw bytes (not a String) so the main isolate never has to hold or
/// decode the ~18k-line text at all — only the small binary asset read.
_ParsedSongs _parseSortAndIndex(Uint8List bytes) {
  final raw = utf8.decode(bytes);
  final jsonList = jsonDecode(raw) as List<dynamic>;
  final songs = jsonList
      .map<SongModel>((json) => SongModel.fromJson(json))
      .toList();
  final sorted = _sortRecursive(songs);

  final lookup = <String, Map<AudioServer, String>>{};
  _buildLookup(lookup, sorted, 'root');

  return _ParsedSongs(sorted, lookup);
}

// ---------------------------------------------------------------------------

class SongRepoImpl implements SongRepository {
  final SharedPreferences sharedPreferences;
  final NetworkInfo networkInfo;
  final http.Client client;
  final Box<SongModel> songsBox;
  final Box<CachedAudioData> downloadedAudioBox;
  final Box<CachedImageData> imageCacheBox;
  final serverManager = ServerManager();

  /// The live song tree. Built once in [initializeServers]. `loadSongs()`
  /// mutates this in place (via `applyCachedData`) rather than deep-copying
  /// it — that copy used to cost a full second JSON round-trip through an
  /// isolate for no benefit, since applyCachedData just re-syncs fields from
  /// Hive every time anyway and is safe to re-run.
  List<SongModel> _mergedTree = [];

  /// key = "$parentId|$songName" -> {AudioServer.server1: url, ...}
  final Map<String, Map<AudioServer, String>> _audioUrlLookup = {};

  SongRepoImpl({
    required this.sharedPreferences,
    required this.networkInfo,
    required this.client,
    required this.songsBox,
    required this.downloadedAudioBox,
    required this.imageCacheBox,
  });

  /// Loads assets/merged_songs.json (generated by merge_song_servers.py) as
  /// raw bytes and hands the whole parse/sort/index pipeline to a single
  /// background isolate call. Call this once at startup before loadSongs().
  Future<void> initializeServers() async {
    final stopwatch = Stopwatch()..start();

    final data = await rootBundle.load('assets/merged_songs.json');
    final bytes = data.buffer.asUint8List(
      data.offsetInBytes,
      data.lengthInBytes,
    );
    debugPrint('[startup] asset read: ${stopwatch.elapsedMilliseconds}ms');

    final parsed = await compute(_parseSortAndIndex, bytes);
    debugPrint(
      '[startup] parse+sort+index (isolate): ${stopwatch.elapsedMilliseconds}ms',
    );

    _mergedTree = parsed.tree;
    _audioUrlLookup
      ..clear()
      ..addAll(parsed.lookup);

    debugPrint(
      '[startup] initializeServers total: ${stopwatch.elapsedMilliseconds}ms',
    );
  }

  void applyCachedData(List<SongModel> songs) {
    for (final song in songs) {
      final audioCache = downloadedAudioBox.get(song.id);

      if (audioCache != null) {
        song.audioLocalPath = audioCache.localPath;
        song.isDownloaded = true;
      }

      final imageCache = imageCacheBox.get(song.id);

      if (imageCache != null) {
        song.imageLocalPath = imageCache.imagePath;
      }

      if (song.children.isNotEmpty) {
        applyCachedData(song.children);
      }
    }
  }

  @override
  Future<String> changeTheme(String theme) {
    return Future.value(
      sharedPreferences.setString('theme', theme).then((value) => theme),
    );
  }

  @override
  Future<String> getCurrentTheme() {
    return Future.value(sharedPreferences.getString('theme') ?? 'dark');
  }

  @override
  Future<List<SongModel>> loadSongs() async {
    try {
      if (_mergedTree.isEmpty) {
        return Future.error(
          "Songs not initialized — call initializeServers() first",
        );
      }

      final stopwatch = Stopwatch()..start();

      // Cheap, O(n) over ~1000 nodes, safe to re-run: re-syncs isDownloaded/
      // localPath flags straight from the Hive boxes. No isolate needed.
      applyCachedData(_mergedTree);

      final freshRoot = SongModel(
        id: 'root',
        name: 'Root',
        listHere: true,
        url: null,
        isAudio: false,
        children: _mergedTree,
      );

      // Fire-and-forget: the UI already has the songs in hand, no need to
      // block startup on the Hive disk write completing.
      unawaited(
        songsBox
            .put('root', freshRoot)
            .catchError((e) => debugPrint('songsBox.put failed: $e')),
      );

      debugPrint('[startup] loadSongs: ${stopwatch.elapsedMilliseconds}ms');
      return _mergedTree;
    } catch (e) {
      return Future.error("Error loading songs: $e");
    }
  }

  /// ---------------------------------------------------------------------
  /// FIX: images sometimes failing to render after the app is closed and
  /// reopened.
  ///
  /// Root cause: this method used to store the `imagePath` it was handed
  /// as-is. That path comes straight from the image picker, which returns
  /// a file living in a TEMPORARY/CACHE directory (NSTemporaryDirectory on
  /// iOS, a cache dir on Android). The OS is free to wipe that directory
  /// at any time — on app relaunch, under memory pressure, etc — and there
  /// is no guarantee it will still be there later. When it gets swept,
  /// `File(imageLocalPath).exists()` starts returning false and the UI
  /// silently falls back to the placeholder, which is exactly the
  /// "sometimes doesn't render" behavior.
  ///
  /// Fix: copy the picked file into the app's Documents directory (the
  /// same durable location already used for downloaded audio) before
  /// caching its path. Documents directory content persists across app
  /// restarts and isn't cleared by the OS.
  /// ---------------------------------------------------------------------
  @override
  Future<List<SongModel>> saveImageLocally(
    SongModel song,
    String imagePath,
  ) async {
    try {
      final root = songsBox.get('root');
      if (root == null) return Future.error("Root not found");

      final sourceFile = File(imagePath);
      if (!await sourceFile.exists()) {
        return Future.error("Picked image no longer exists: $imagePath");
      }

      final docsDir = await getApplicationDocumentsDirectory();
      final imagesDir = Directory('${docsDir.path}/Images');
      await imagesDir.create(recursive: true);

      // Keep the original extension, default to .jpg if there isn't one.
      final dot = imagePath.lastIndexOf('.');
      final ext = dot != -1 ? imagePath.substring(dot) : '.jpg';

      // Name the file after the song id so re-picking an image for the
      // same song overwrites its old file instead of accumulating orphans.
      final destPath = '${imagesDir.path}/${song.id}$ext';
      final destFile = await sourceFile.copy(destPath);

      await imageCacheBox.put(
        song.id,
        CachedImageData(songId: song.id, imagePath: destFile.path),
      );
      song.imageLocalPath = destFile.path;
      return Future.value(root.children);
    } catch (e) {
      return Future.error("Error saving image locally: $e");
    }
  }

  @override
  Stream<Either<Failure, DownloadAudioReport>> downloadAudio(
    SongModel child,
    SongModel parent,
  ) async* {
    if (!await networkInfo.isConnected) {
      yield Left(ServerFailure(message: "No internet connection!!!"));
      return;
    }

    final key = '${parent.id}|${child.name}';
    final urls = _audioUrlLookup[key];

    if (urls == null || urls.isEmpty) {
      yield Left(ServerFailure(message: "Song not found on any server."));
      return;
    }

    bool downloaded = false;

    /// Helper: download a single URL with progress
    Stream<Either<Failure, DownloadAudioReport>> downloadStream(
      SongModel parent,
      SongModel child,
      String url, {
      bool emitErrors = true,
    }) async* {
      try {
        final request = http.Request('GET', Uri.parse(url));
        final response = await client.send(request);

        if (response.statusCode != 200) {
          if (emitErrors) {
            yield Left(ServerFailure(message: 'Failed to download file.'));
          }
          return; // silently fail if emitErrors == false
        }

        final dir = await getApplicationDocumentsDirectory();
        final path = '${dir.path}/Audio/${parent.id.replaceAll("/", "_")}';
        await Directory(path).create(recursive: true);
        final file = File('$path/${decodeAndTrimUrl(url)}');

        int downloadedBytes = 0;
        final total = response.contentLength ?? 0;
        final sink = file.openWrite();

        await for (final chunk in response.stream) {
          downloadedBytes += chunk.length;
          sink.add(chunk);

          double progress = total > 0 ? downloadedBytes / total : 0;
          yield Right(
            DownloadAudioReport(songModel: parent, progress: progress * 100),
          );
        }

        await sink.close();

        await downloadedAudioBox.put(
          child.id,
          CachedAudioData(songId: child.id, localPath: file.path),
        );
        child.isDownloaded = true;
        child.audioLocalPath = file.path;
        yield Right(DownloadAudioReport(progress: 100, songModel: parent));
      } catch (e) {
        if (emitErrors) {
          yield Left(ServerFailure(message: e.toString()));
        }
      }
    }

    // Try up to N servers (N = number of servers configured), starting from
    // wherever the round-robin index currently is, skipping any server that
    // doesn't have this particular song. Stops as soon as one succeeds.
    for (
      int attempt = 0;
      attempt < serverManager.servers.length && !downloaded;
      attempt++
    ) {
      final server = serverManager.next();
      final url = urls[server];
      if (url == null) continue; // this server doesn't have this song

      await for (final event in downloadStream(
        parent,
        child,
        url,
        emitErrors: false,
      )) {
        yield event; // emit every progress update

        final progressValue = event
            .getOrElse(
              () => DownloadAudioReport(songModel: parent, progress: 0),
            )
            .progress;
        if (progressValue == 100) {
          downloaded = true;
        }
      }
    }

    // All servers failed
    if (!downloaded) {
      yield Left(
        ServerFailure(
          message:
              "Monthly download limit reached. Support the project to help us increase capacity and bring servers back sooner.",
        ),
      );
    }
  }

  @override
  Future<bool> isConnected() async {
    return await networkInfo.isConnected;
  }

  @override
  Future<void> submitFeedback({
    required String feedback,
    required String fullname,
    File? imageFile,
  }) async {
    final token = dotenv.env['TELEGRAM_BOT_TOKEN'];
    final userId = dotenv.env['USER_ID'];

    if (token == null || userId == null) {
      throw Exception('Bot token or user ID not configured in .env');
    }

    final caption =
        '''
*New Feedback*

*Message:*  
$feedback

*Telegram:*  
@$fullname
  '''
            .trim();

    try {
      if (imageFile != null) {
        final uri = Uri.parse('https://api.telegram.org/bot$token/sendPhoto');
        final request = http.MultipartRequest('POST', uri);

        request.fields['chat_id'] = userId;
        request.fields['caption'] = caption;
        request.fields['parse_mode'] = 'Markdown';

        final bytes = await imageFile.readAsBytes();
        final multipartFile = http.MultipartFile.fromBytes(
          'photo',
          bytes,
          filename: imageFile.path.split(Platform.pathSeparator).last,
        );

        request.files.add(multipartFile);

        final response = await request.send();

        if (response.statusCode != 200) {
          final errorBody = await response.stream.bytesToString();
          throw Exception(
            'Failed to send photo: ${response.statusCode} - $errorBody',
          );
        }
      } else {
        final uri = Uri.parse('https://api.telegram.org/bot$token/sendMessage');
        final response = await http.post(
          uri,
          body: {'chat_id': userId, 'text': caption, 'parse_mode': 'Markdown'},
        );

        if (response.statusCode != 200) {
          throw Exception('Failed to send message: ${response.statusCode}');
        }
      }
    } catch (e) {
      throw Exception('Failed to send feedback. Please try again.');
    }
  }

  Future<String> getAudioUrlFromServer(
    AudioServer server,
    String parentPath,
    String audioName,
  ) async {
    final key = '$parentPath|$audioName';

    final urls = _audioUrlLookup[key];
    if (urls == null) {
      throw Exception("Song not found: $key");
    }

    final url = urls[server];
    if (url == null) {
      throw Exception("Audio not found on $server for $key");
    }

    return url;
  }

  SongModel? findAudioRecursively(List<SongModel> songs, String audioName) {
    for (final song in songs) {
      if (song.name == audioName && song.isAudio == true) {
        return song;
      }

      final deeper = findAudioRecursively(song.children, audioName);
      if (deeper != null) return deeper;
    }
    return null;
  }

  SongModel? findParentFolder(List<SongModel> songs, String parentPath) {
    for (final song in songs) {
      if (song.id == parentPath) return song;

      final deeper = findParentFolder(song.children, parentPath);
      if (deeper != null) return deeper;
    }
    return null;
  }
}

String decodeAndTrimUrl(String url) {
  final decoded = Uri.decodeFull(url);
  final filename = decoded.substring(decoded.lastIndexOf('/') + 1);
  final match = RegExp(r'^(.*)_[^_]+(\.\w+)$').firstMatch(filename);
  return match != null ? '${match.group(1)}${match.group(2)}' : filename;
}
